#!/usr/bin/bash

# Exit if any errors occur
set -e

# Build for production
bun run build

# Push to the main branch
git add .
git commit -m "New build deployment"
git push

# Force push the build to the `github-pages` branch
git push origin `git subtree split --prefix build main`:github-pages --force